### ISSUE TITLE
How to configure the checkout page

### ISSUE THREAD

**Issue by mfprogrammer** [icepay/API#2]
Hi, 
Can we configure the checkout page to the look and feel of my website?
If yes, how can we do so?

Thanks.

**Comment by tsygankov** [comment]
Hi mfprogrammer,

This project (repository) is for REST API integration library that can be used in any PHP website. This project does not contain any UI templates.

I guess your question is related to a specific web-shop platform (for example Magento, Prestashop, OsCommerce and etc)? In this case please create an issue in the [project ](https://github.com/ICEPAYdev) dedicated to the specific platform.

Thank you!

**Comment by mfprogrammer** [comment]
Hi @tsygankov i am using this rest api to integrate the gateway with my website.
I have a custom made php website. hence, i do not use a specific website.
I just want to design the payment page. Can you please direct me in the right direction.
Thanks.
