### ISSUE TITLE
Inconsistency between Manual and Apiary-docs

### ISSUE THREAD

**Issue by LeonidasJP** [icepay/API#4]
While building and testing our implementation of Icepay, we discovered an inconsistency between the [REST API Implementation Manual v1.2.2](https://icepay.com/app/uploads/ICEPAY-REST-API-Implementation-manual-v1.22.pdf) and the [Apiary Documentation](https://icepay.docs.apiary.io/#reference/0/payments/checkout); concerning the length of the OrderID in transactions.

The Implementation Manual mentions a maximum OrderID length of 10 characters, but the Apiary docs mention a maximum OrderID length of 20 characters. The limit of 10 characters seems to be enforced on database-level, without warning the API-consumer their OrderID has been truncated.

The OrderIDs in our software are 10 to 20 characters; they consist of:
* An optional administrative prefix of up to 5 alphanumeric characters
* The Unix Timestamp of when the order has been placed (10 numbers)
* An optional random number between 10000 and 99999 for busy shops (with multiple orders per second) to make sure those orders are considered unique
Especially Orders with an administrative prefix are having issues, limiting the number of transactions to 1 per 2h45m when a four-character prefix is in use, due to the Timestamp being truncated.

Is it possible to:
* Update the API/DB to allow Order IDs up to 20 characters
* Update the Implementation Manual to reflect the 20-character limit
or:
* Update the Apiary docs to reflect the 10-character limit?

Sincerely,
Leon Hagendijk
Logivert

**Comment by ghost** [comment]
Hi Leon,

Thank you for pointing this out!
Unfortunately our legacy system does have a limit of 10 characters for OrderID. We will update the apiary site accordingly.
Note that we are currently working on a new API (see: http://docs2.icepay.com) that does not have this limit.

Regards,
ICEPAY

**Comment by LeonidasJP** [comment]
Clear! Thanks for the quick response!
For now I will limit the OrderID I send in to the timestamp of ordering (eg. 10 characters).

Is the v2-API already available for use, or is it still work-in-progress and should I consider it as Alpha/Unstable at the moment?

**Comment by LeonidasJP** [comment]
I am now trying to use the URLPostback-parameter, as mentioned on [Apiary](https://icepay.docs.apiary.io/#reference/0/payments/checkout) to make sure the Postbacks are processed correctly. For each payment we are generating a URL (/payment/notify/`Full order ID`).

Only, this parameter gets refused. Is this parameter not supported and included on Apiary by mistake?

**Comment by ghost** [comment]
The URLPostback parameter is actually an array of strings, allowing you to pass multiple urls. This was incorrectly documented on Apiary, thank you for pointing this out. This parameter is only supported for our REST API (not our SOAP API).

Our v2-API is currently in Beta, we expect a full release at the end of next month.

**Comment by LeonidasJP** [comment]
Ah, that's why it got refused... Thanks for amending Apiary.
We'll be transitioning to the v2-API in the near future, do you have any indication when the Legacy-API will be turned off?

**Comment by LeonidasJP** [comment]
I am now posting this Payment to Icepay:
```php
[
  "PaymentMethod" => "IDEAL",
  "Amount" => 1026,
  "Country" => "nl",
  "Currency" => "eur",
  "Description" => "1547634982",
  "Issuer" => "RABOBANK",
  "Language" => "nl",
  "OrderID" => 1547634982,
  "Reference" => "1547634982",
  "URLCompleted" => "https://example.com/payment/success/1547634982",
  "URLError" => "https://example.com/payment/cancel/1547634982",
  "URLPostback" => [
    "https://example.com/payment/notify/1547634982",
  ],
  "EndUserIP" => "xxx.xxx.xxx.xxx",
  "Timestamp" => "2019-01-16T10:01:22Z",
]
```
But, the Test Transaction endpoint always seem to post back to `https://example.com/payment/notify/`, without the Order ID. This URL is the one set in the Webshop Settings. Is this an error in the API, or am I submitting something wrong?

**Comment by ghost** [comment]
I checked your transactions. I noticed you specified a customer Notification URLs for your transactions today, however only in the last attempt did you specify a full URL. The other transactions only had relative urls (e.g. /leon/app_dev.php/payment/notify/1547634843) which doesn't work.
The transaction with the full url was not completed so no postback was sent.

**Comment by LeonidasJP** [comment]
Ah, I see. Just ran the open test transactions. One was from my example above, that went OK. Seems Test Transaction overview only mentions the URLs supplied in the Backend, not those that were submitted in the Payment Request... Therefore my confusion.

**Comment by ghost** [comment]
Fair point, the Test Transactions overview does not display the incorrect URL in case of a Customer Notification URL.  I have created a ticket for this issue.

**Comment by LeonidasJP** [comment]
Thanks for the help and the feedback!
